# Generated by Django 3.2.8 on 2022-01-01 00:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminname', models.CharField(max_length=20, verbose_name='管理员用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日期')),
                ('face', models.CharField(default='img/test.jpg', max_length=255, verbose_name='头像')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('policeid', models.CharField(max_length=19, null=True, verbose_name='警号')),
                ('idcard', models.CharField(max_length=19, null=True, verbose_name='身份证号')),
                ('realName', models.CharField(max_length=50, null=True, verbose_name='真实姓名')),
            ],
            options={
                'db_table': 'police',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日期')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Yawn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='0', max_length=19, verbose_name='哈欠次数')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='起始日期')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='终止日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.user')),
            ],
            options={
                'db_table': 'yawn',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server.user')),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(default='新用户', max_length=50, verbose_name='昵称')),
                ('face', models.CharField(default='img/test.jpg', max_length=255, verbose_name='头像')),
                ('realName', models.CharField(max_length=50, null=True, verbose_name='真实姓名')),
                ('idcard', models.CharField(max_length=19, null=True, verbose_name='身份证号')),
                ('drivercard', models.CharField(max_length=13, null=True, verbose_name='驾驶证号')),
                ('carcard', models.CharField(max_length=20, null=True, verbose_name='车牌号')),
                ('sex', models.IntegerField(default=0, verbose_name='性别')),
                ('birth', models.DateField(null=True, verbose_name='生日')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server.user')),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
        migrations.CreateModel(
            name='Tired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(default='0', max_length=19, verbose_name='疲劳指数')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='起始日期')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='终止日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.user')),
            ],
            options={
                'db_table': 'tired',
            },
        ),
        migrations.CreateModel(
            name='Smoke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='起始日期')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='终止日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.user')),
            ],
            options={
                'db_table': 'smoke',
            },
        ),
        migrations.CreateModel(
            name='PoliceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('police', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server.police')),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='起始日期')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='终止日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiles', to='server.user')),
            ],
            options={
                'db_table': 'mobile',
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='起始日期')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='终止日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.user')),
            ],
            options={
                'db_table': 'drink',
            },
        ),
        migrations.CreateModel(
            name='Blink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='0', max_length=19, verbose_name='眨眼次数')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='起始日期')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='终止日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.user')),
            ],
            options={
                'db_table': 'blink',
            },
        ),
        migrations.CreateModel(
            name='AdminToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server.admin')),
            ],
        ),
    ]
