# Generated by Django 3.2.8 on 2022-01-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birth',
            field=models.DateTimeField(null=True, verbose_name='生日'),
        ),
    ]
